<?php
//全局插件设置选项 --------------
$__XWB_SET=array (
  'wb_addr_display' => 0,
  'is_wbx_display' => 0,
  'wbx_width' => 180,
  'wbx_height' => 500,
  'wbx_style' => 4,
  'wbx_line' => 2,
  'wbx_is_title' => 1,
  'wbx_is_blog' => 1,
  'wbx_is_fans' => 1,
  'wbx_url' => 'http://service.t.sina.com.cn/widget/WeiboShow.php?uname=xweibo%E6%B5%8B%E8%AF%95%E5%B8%90%E5%8F%B7&width=180&height=500&skin=4&isTitle=1&isWeibo=1&isFans=1&fansRow=2&__noCache=1303314319940',
  'is_account_binding' => 1,
  'is_synctopic_toweibo' => 1,
  'is_syncreply_toweibo' => 1,
  'is_syncdoing_toweibo' => 1,
  'is_syncblog_toweibo' => 1,
  'is_syncshare_toweibo' => 1,
  'is_syncarticle_toweibo' => 1,
  'is_rebutton_display' => 0,
  'is_tips_display' => 0,
  'is_signature_display' => 1,
  'is_sync_face' => 0,
  'is_upload_image' => 1,
  'wbx_medal_update_time' => 1800,
  'wbx_share_time' => 15,
  'is_display_login_button' => 0,
  'link_visit_promotion' => 0,
  'wbx_huwb_update_time' => 24,
  'is_pushback_open' => 0,
  'pushback_authkey' => '',
  'pushback_to_thread' => 0,
  'pushback_to_blog' => 0,
  'pushback_to_doing' => 0,
  'pushback_to_article' => 0,
  'pushback_to_share' => 0,
  'pushback_fromid' => 0,
  'bind_btn_usernav' => 0,
  'pushback_username' => '',
  'pushback_uid' => 0,
);
?>